```{r header, fig.show='hide'}
#   title: 'Reproducible Research: Peer Assessment 1'

```


```{ r loadlibrary, fig.show='hide'}
## Loading and preprocessing the data
library(knitr)
knitr::opts_chunk$set(echo=TRUE)
library(chron)
```

```{r total_steps_histogram, fig.show='hold'}
activityData <- read.csv(file="activity.csv")

activityData$date <-as.Date(activityData$date, format="%Y-%m-%d")



## What is mean total number of steps taken per day?


AggregatedData<-aggregate(activityData$steps, list(activityData$date), sum, na.rm=TRUE)
colnames(AggregatedData) <- c("date", "steps")

hist(AggregatedData$steps,breaks=10, main="Histogram of total steps per day", xlab="Total steps per day", ylab="Frequency")


mean_per_day<-mean(AggregatedData$steps, na.rm=TRUE)

median_per_day<-median(AggregatedData$steps, na.rm=TRUE)
```

```{r average_daily_pattern, fig.show='hold'}
## What is the average daily activity pattern?

timeseries_steps<-aggregate(activityData$steps, list(activityData$interval), mean, na.rm=TRUE)
colnames(timeseries_steps) <- c("interval", "steps")
plot(timeseries_steps$interval,timeseries_steps$steps, type="l", xlab="5-minute Interval", ylab="Mean of steps")

timeseries_steps$interval[which.max(timeseries_steps$steps)]
```

```{r impute_missing_values, fig.show='hold'}
## Imputing missing values

sum(is.na(activityData$steps) == TRUE)

activityData$fixed_steps <- ifelse(is.na(activityData$steps), round(timeseries_steps$steps[match(activityData$interval, timeseries_steps$interval)], 0), activityData$steps)
head(activityData, n=20)

new_dataset<-data.frame(steps=activityData$fixed_steps, date=activityData$date, interval=activityData$interval)

fixed_AggregatedData<-aggregate(new_dataset$steps, list(new_dataset$date), sum, na.rm=TRUE)
colnames(fixed_AggregatedData) <- c("date", "fixed_steps")
hist(fixed_AggregatedData$fixed_steps,breaks=10, main="Histogram of the total steps", xlab="steps (correced the missing steps)", ylab="Frequency")

fixed_mean_per_day<-mean(fixed_AggregatedData$fixed_steps, na.rm=TRUE)

fixed_median_per_day<-median(fixed_AggregatedData$fixed_steps, na.rm=TRUE)
```

```{r difference_daily_patterns, fig.show='hold'}

library(chron)
packageVersion("chron") 
library(ggplot2)

## Are there differences in activity patterns between weekdays and weekends?

new_dataset$daytype <- ifelse(is.weekend(new_dataset$date),"weekend", "weekday")
daytype_interval<-aggregate(steps ~ interval + daytype, new_dataset, mean, na.rm=TRUE)

ggplot(daytype_interval, aes(interval, steps)) + 
  geom_line() + xlab("Interval") + ylab("Mean of steps") + facet_grid(daytype ~ .)

```
